# render.yaml for ExpenseWise Django project

services:
  - type: web
    name: expensewise-web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn expensewebsite.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: expensewise-db
    type: mysql
    plan: free
